# Twig Configuration
parameters:
    no_user_found          : "User not existed"
    user_authorize         : "This User not Authorised to send messages"
    message_succ           : "Message sent successfully!"
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:        
        todo_list_not_found: "Todo List Not Found"
        no_messages        : "No Messages Found"
        no_applicants      : "No Applicants Found"
        delete_evidence_confirm: "Are you want to delete the evidence?"
