# Twig Configuration
parameters:
    no_user_found          : "User not existed"
    user_authorize         : "This User not Authorised to send messages"
    message_succ           : "Message sent successfully!"
    passwd_succ            : "Password updated successfully!"
    curr_pwd               : "Current Password is not correct!"
    no_match_pwd           : "New Password and Confirm Password does not match"
    profile_update         : "Profile updated successfully!"
    fac_update_succ        : "Facilitator assigned successfully!"
    ass_update_succ        : "Assessor assigned successfully!"
    rto_update_succ        : "RTO assigned successfully!"
    err_update             : "Error while updating.."
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:        
        todo_list_not_found: "Todo List Not Found"
        no_messages        : "No Messages Found"
        no_applicants      : "No Applicants Found"
        no_id_files        : "No Id files found"
        delete_evidence_confirm: "Do you want to delete?"
        usi_link           : "Don't have one? Click here to create one"
        todo_status_change : "Do you want to change the status?"
        no_evidences_found : "No Evidences Found"
        still_processing : "Still Processing"
