_wdt:
    resource: "@WebProfilerBundle/Resources/config/routing/wdt.xml"
    prefix:   /_wdt

_profiler:
    resource: "@WebProfilerBundle/Resources/config/routing/profiler.xml"
    prefix:   /_profiler

_configurator:
    resource: "@SensioDistributionBundle/Resources/config/routing/webconfigurator.xml"
    prefix:   /_configurator

_errors:
    resource: "@TwigBundle/Resources/config/routing/errors.xml"
    prefix:   /_error

_main:
    resource: routing.yml

# GqAusUserBundle routes (to be removed)
_default_page:
    resource: "@GqAusUserBundle/Resources/config/routing.yml"

login:
    path:     /login
    defaults:  { _controller: GqAusUserBundle:Login:index }
login_check:
    path: /login_check
