user:
    resource: "@GqAusUserBundle/Resources/config/routing.yml"
    prefix:   /

dashboard:
    resource: "@GqAusHomeBundle/Resources/config/routing.yml"
    prefix:   /

# GqAusUserBundle routes (to be removed)
_default_page:
    resource: "@GqAusUserBundle/Resources/config/routing.yml"

login:
    path:     /login
    defaults:  { _controller: GqAusUserBundle:Login:index }
login_check:
    path: /login_check
logout:
    path:     /logout
    defaults:  { _controller: GqAusUserBundle:Login:logout }

