user:
    resource: "@GqAusUserBundle/Resources/config/routing.yml"
    prefix:   /
login:
    path:     /login
    defaults:  { _controller: GqAusUserBundle:Login:index }
login_check:
    path: /login_check
logout:
    path:     /logout
    defaults:  { _controller: GqAusUserBundle:Login:logout }
dashboard:
    resource: "@GqAusHomeBundle/Resources/config/routing.yml"
    prefix:   /
