# app/config/security.yml
security:
    firewalls:
        secured_area:
            pattern:    ^/
            anonymous: ~
            form_login: ~
            logout:
               path:   _demo_logout
               target: _demo
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/forgotpassword, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/dashboard, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/userprofile, roles: IS_AUTHENTICATED_FULLY }
    providers:
        main:
            entity: {class: GqAusUserBundle:User, property: email}
    encoders:
        GqAus\UserBundle\Entity\User: 
            algorithm: bcrypt

