# app/config/security.yml
security:
    firewalls:
        secured_area:
            pattern:    ^/
            anonymous: ~
            form_login: ~
            logout:
               path:   _logout
               target: _login
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/forgotpassword, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/dashboard, roles: [ROLE_FACILITATOR, ROLE_ASSESSOR, ROLE_RTO, ROLE_MANAGER, ROLE_SUPERADMIN] }
        - { path: ^/qualificationDetails/.*, roles: ROLE_APPLICANT }
        - { path: ^/qualifications, roles: ROLE_APPLICANT }
        - { path: ^/evidences, roles: [ROLE_APPLICANT, ROLE_FACILITATOR] } 
        - { path: ^/userprofile, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/applicantDetails/.*, roles: [ROLE_FACILITATOR, ROLE_ASSESSOR, ROLE_RTO, ROLE_MANAGER, ROLE_SUPERADMIN] }
        - { path: ^/applicants, roles: [ROLE_FACILITATOR, ROLE_ASSESSOR, ROLE_RTO, ROLE_MANAGER, ROLE_SUPERADMIN] }
        - { path: ^/reminder, roles: [ROLE_FACILITATOR, ROLE_ASSESSOR] }
        - { path: ^/messages/*, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/compose, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/sent, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/trash, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/view, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/viewUserIdFiles, roles: ROLE_FACILITATOR }
        - { path: ^/reports, roles: [ROLE_MANAGER, ROLE_SUPERADMIN] }
        - { path: ^/downloadFiles, roles: [ROLE_ASSESSOR, ROLE_RTO] }
        - { path: ^/zipFiles, roles: [ROLE_ASSESSOR, ROLE_RTO] }
        - { path: ^/startConversation, roles: ROLE_ASSESSOR }
        - { path: ^/startConversation, roles: ROLE_ASSESSOR }
        - { path: ^/startArchive, roles: ROLE_ASSESSOR }
        - { path: ^/stopArchive, roles: ROLE_ASSESSOR }
        - { path: ^/viewEvidence, roles: [ROLE_ASSESSOR, ROLE_RTO] }
        - { path: ^/viewIdFile, roles: [ROLE_ASSESSOR, ROLE_RTO] }
        - { path: ^/manageusers, roles: [ROLE_MANAGER, ROLE_SUPERADMIN] }
        - { path: ^/managemanagers, roles: [ROLE_SUPERADMIN] }
        - { path: ^/addUser/.*, roles: [ROLE_MANAGER, ROLE_SUPERADMIN] }
        - { path: ^/editUser/.*, roles: [ROLE_MANAGER, ROLE_SUPERADMIN] }
        - { path: ^/courseunitDetails/.*, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/files/.*, roles: IS_AUTHENTICATED_FULLY }
    access_denied_url: /unauthorized
    providers:
        main:
            entity: {class: GqAusUserBundle:User, property: email}
    encoders:
        GqAus\UserBundle\Entity\User:
            algorithm: bcrypt
           