user_homepage:
    path:     /user
    defaults: { _controller: GqAusUserBundle:Default:index }
_page:
    path:     /
    defaults: { _controller: GqAusUserBundle:Login:index }
forgotpassword:
    path:     /forgotpassword
    defaults:  { _controller: GqAusUserBundle:ForgotPassword:index }
resetPassword:
    path:     /resetpassword/{token}
    defaults:  { _controller: GqAusUserBundle:ForgotPassword:resetPassword }