user_homepage:
    path:     /userprofile
    defaults: { _controller: GqAusUserBundle:User:profile }
_page:
    path:     /
    defaults: { _controller: GqAusUserBundle:Login:index }
forgotpassword:
    path:     /forgotpassword
    defaults:  { _controller: GqAusUserBundle:ForgotPassword:index }
resetPassword:
    path:     /resetpassword/{token}
    defaults:  { _controller: GqAusUserBundle:ForgotPassword:resetPassword }
id_file_upload:
    path:     /idfileupload
    defaults: { _controller: GqAusUserBundle:User:addIdFile }
add_evidence:
    path:     /addEvidences
    defaults: { _controller: GqAusUserBundle:Evidence:add }
view_evidences:
    path:     /evidences
    defaults: { _controller: GqAusUserBundle:Evidence:view }
saveExistingEvidence:
    path:     /saveExistingEvidence
    defaults: { _controller: GqAusUserBundle:Evidence:saveExistingEvidence }
deleteEvidenceFile:
    path:     /deleteEvidenceFile
    defaults:  { _controller: GqAusUserBundle:Evidence:deleteEvidenceFile }
deleteIdFiles:
    path:     /deleteIdFiles
    defaults:  { _controller: GqAusUserBundle:User:deleteIdFiles }
uploadProfilePic:
    path:     /uploadProfilePic
    defaults: { _controller: GqAusUserBundle:User:uploadProfilePic }
checkMyPassword:
    path:     /checkMyPassword
    defaults: { _controller: GqAusUserBundle:User:checkMyPassword }