acceptOnBoarding:
    path:     /acceptOnBoarding
    defaults: { _controller: GqAusUserBundle:Authenticate:acceptOnBoarding }
firstTimeSetPassword:
    path:     /firstTimeSetPassword
    defaults: { _controller: GqAusUserBundle:Authenticate:firstTimeSetPassword }
onBoarding:
    path:     /onBoarding/{loginToken}
    defaults: { _controller: GqAusUserBundle:Authenticate:onBoarding }
validateUser:
    path:     /validateUser/{loginToken}
    defaults: { _controller: GqAusUserBundle:Authenticate:validateUser }
user_homepage:
    path:     /userprofile
    defaults: { _controller: GqAusUserBundle:User:profile }
_page:
    path:     /
    defaults: { _controller: GqAusUserBundle:Login:index }
forgotpassword:
    path:     /forgotpassword
    defaults:  { _controller: GqAusUserBundle:ForgotPassword:index }
resetPassword:
    path:     /resetpassword/{token}
    defaults:  { _controller: GqAusUserBundle:ForgotPassword:resetPassword }
id_file_upload:
    path:     /idfileupload
    defaults: { _controller: GqAusUserBundle:User:addIdFile }
addEnrollmentForm:
    path:     /addEnrollmentForm
    defaults: { _controller: GqAusUserBundle:User:addEnrollmentForm }
add_evidence:
    path:     /addEvidences
    defaults: { _controller: GqAusUserBundle:Evidence:add }
view_evidences:
    path:     /evidences
    defaults: { _controller: GqAusUserBundle:Evidence:view }
saveExistingEvidence:
    path:     /saveExistingEvidence
    defaults: { _controller: GqAusUserBundle:Evidence:saveExistingEvidence }
deleteEvidenceFile:
    path:     /deleteEvidenceFile
    defaults:  { _controller: GqAusUserBundle:Evidence:deleteFile }
deleteIdFiles:
    path:     /deleteIdFiles
    defaults:  { _controller: GqAusUserBundle:User:deleteIdFiles }
uploadProfilePic:
    path:     /uploadProfilePic/{userId}
    defaults: { _controller: GqAusUserBundle:User:uploadProfilePic }
applicants:
    path:     /applicants
    defaults: { _controller: GqAusUserBundle:Applicant:applicantsList }
applicantDetails:
    path:     /applicantDetails/{qcode}/{uid}
    defaults: { _controller: GqAusUserBundle:Applicant:details }
courseunitDetails:
    path:     /courseunitDetails/{qcode}/{unitcode}/{uid}
    defaults: { _controller: GqAusUserBundle:Applicant:courseunitDetails }
courseUnitMobDetails:
    path:     /courseUnitMobDetails/{qcode}/{unitcode}/{uid}
    defaults: { _controller: GqAusUserBundle:Applicant:courseUnitMobDetails }
getUnitEvidences:
    path:     /getUnitEvidences
    defaults:  { _controller: GqAusUserBundle:Qualification:getUnitEvidences }
setUserUnitEvidencesStatus:
    path:     /setUserUnitEvidencesStatus
    defaults:  { _controller: GqAusUserBundle:Applicant:setUserUnitEvidencesStatus }
checkMyPassword:
    path:     /checkMyPassword
    defaults: { _controller: GqAusUserBundle:User:checkMyPassword }
editEvidenceTitle:
    path:     /editEvidenceTitle
    defaults:  { _controller: GqAusUserBundle:Evidence:editTitle }
addReminder:
    path:     /addReminder
    defaults:  { _controller: GqAusUserBundle:Applicant:addReminder }
searchApplicantsList:
    path:     /searchApplicantsList
    defaults:  { _controller: GqAusUserBundle:Applicant:searchApplicantsList }
searchApplicantsListReports:
    path:     /searchApplicantsListReports
    defaults:  { _controller: GqAusUserBundle:Applicant:searchApplicantsListReports }
searchApplicantsListByGridHeadings:
    path:     /searchApplicantsListByGridHeadings
    defaults:  { _controller: GqAusUserBundle:Applicant:searchApplicantsListByGridHeadings }
createzip:
    path:     /zipFiles/{qcode}/{uid}
    defaults:  { _controller: GqAusUserBundle:Applicant:zip }
downloadFiles:
    path:     /downloadFiles/{qcode}/{uid}
    defaults: { _controller: GqAusUserBundle:Applicant:download }
reminder:
    path:     /reminder
    defaults: { _controller: GqAusUserBundle:Reminder:view }
updateTodo:
    path:     /updateTodo
    defaults: { _controller: GqAusUserBundle:Reminder:update }
resume_upload:
    path:     /resumeupload
    defaults: { _controller: GqAusUserBundle:User:resume }
qualification_upload:
    path:     /qualificationupload
    defaults: { _controller: GqAusUserBundle:User:qualification }
reference_upload:
    path:     /referenceupload
    defaults: { _controller: GqAusUserBundle:User:reference }
matrix_upload:
    path:     /matrixupload
    defaults: { _controller: GqAusUserBundle:User:matrix }
deleteOtherFiles:
    path:     /deleteOtherFiles
    defaults:  { _controller: GqAusUserBundle:User:deleteOtherFiles }
download_matrix:
    path:     /downloadMatrix
    defaults:  { _controller: GqAusUserBundle:User:downloadMatrix }
assessor_profile:
    path:     /assessorProfile/{uid}
    defaults:  { _controller: GqAusUserBundle:User:assessorProfile }
download_assessor_profile:
    path:     /downloadAssessorProfile/{uid}
    defaults:  { _controller: GqAusUserBundle:User:downloadAssessorProfile }
messages:
    path:     /messages/{mid}
    defaults: { _controller: GqAusUserBundle:Message:view, mid: null }
compose:
    path:     /compose
    defaults: { _controller: GqAusUserBundle:Message:compose }
usernamesbyRoles:
    path:     /usernamesbyRoles
    defaults: { _controller: GqAusUserBundle:Message:usernamesbyRoles }
addressByField:
    path:     /addressbyField
    defaults: { _controller: GqAusUserBundle:User:addressByField }
sent:
    path:     /sent
    defaults: { _controller: GqAusUserBundle:Message:sent }
trash:
    path:     /trash
    defaults: { _controller: GqAusUserBundle:Message:trash }
draft:
    path:     /draft
    defaults: { _controller: GqAusUserBundle:Message:trash }
markasread:
    path:     /markasread
    defaults: { _controller: GqAusUserBundle:Message:markAsRead }
deleteFromUser:
    path:     /deleteFromUser
    defaults: { _controller: GqAusUserBundle:Message:deleteFromUser }
deleteFromUserSent:
    path:     /deleteFromUserSent
    defaults: { _controller: GqAusUserBundle:Message:deleteFromUserSent }
viewMessage:
    path:     /view/{mid}
    defaults: { _controller: GqAusUserBundle:Message:viewMessage }
deleteFromTrash:
    path:     /deleteFromTrash
    defaults: { _controller: GqAusUserBundle:Message:deleteFromTrash }
unread:
    path:     /unread
    defaults: { _controller: GqAusUserBundle:Message:unread }
approveCertification:
    path:     /approveCertification
    defaults: { _controller: GqAusUserBundle:Applicant:approveCertification }
tokbox:
    path:     /startConversation
    defaults: { _controller: GqAusUserBundle:Tokbox:index }
subscriber:
    path:     /applicant/{roomId}
    defaults: { _controller: GqAusUserBundle:Tokbox:subscriber }
approveForRTO:
    path:     /approveForRTO
    defaults: { _controller: GqAusUserBundle:Applicant:approveForRTO }
approveAllUnitsFromRTO:
    path: /approveAllUnitsFromRTO
    defaults: { _controller: GqAusUserBundle:Applicant:approveAllUnitsFromRTO }
reports:
    path:     /reports
    defaults: { _controller: GqAusUserBundle:Applicant:reports }
startArchive:
    path:     /startArchive/{roomId}
    defaults: { _controller: GqAusUserBundle:Tokbox:start }
stopArchive:
    path:     /stopArchive/{archiveId}/{applicantId}/{unitCode}/{courseCode}
    defaults: { _controller: GqAusUserBundle:Tokbox:stop }
historyArchive:
    path:     /history
    defaults: { _controller: GqAusUserBundle:Tokbox:history }
downloadArchive:
    path:     /downloadArchive/{aid}
    defaults: { _controller: GqAusUserBundle:Tokbox:download }
addApplicant:
    path:     /addApplicant/
    defaults: { _controller: GqAusUserBundle:User:addApplicant }
viewEvidenceApplicant:
    path:     /viewEvidence/{evidenceId}
    defaults: { _controller: GqAusUserBundle:Applicant:viewEvidence }
setRoleUsers:
    path:     /setRoleUsers
    defaults: { _controller: GqAusUserBundle:Applicant:setRoleUsers }
getUserEvidences:
    path:     /getUserEvidences
    defaults:  { _controller: GqAusUserBundle:User:getUserEvidences }
addEvidenceAssessment:
    path:     /addEvidenceAssessment
    defaults:  { _controller: GqAusUserBundle:Evidence:addEvidenceAssessment }
viewUserIdFiles:
    path:     /viewUserIdFiles/{userId}
    defaults: { _controller: GqAusUserBundle:User:viewUserIdFiles }
saveMessage:
    path:     /saveMessage
    defaults: { _controller: GqAusUserBundle:Message:saveMessage }
addNotes:
    path:     /addNotes
    defaults: { _controller: GqAusUserBundle:Notes:addNotes }
getUnitNotes:
    path:     /getUnitNotes
    defaults: { _controller: GqAusUserBundle:Notes:getUnitNotes }
facilitatorApplicant:
    path:     /facilitatorApplicant
    defaults: { _controller: GqAusUserBundle:Message:facilitatorApplicant }
viewIdFileApplicant:
    path:     /viewIdFile/{idFileId}
    defaults: { _controller: GqAusUserBundle:Applicant:viewIdFile }
manageusers:
    path:     /manageusers
    defaults: { _controller: GqAusUserBundle:User:manageusers }
userLogin:
    path:     /userLogin/{userId}
    defaults: { _controller: GqAusUserBundle:Authenticate:userLogin }
searchUsersList:
    path:     /searchUsersList
    defaults: { _controller: GqAusUserBundle:User:searchUsersList }
deleteUser:
    path:     /deleteUser
    defaults: { _controller: GqAusUserBundle:User:deleteUser }
editUser:
    path:     /editUser/{uId}
    defaults: { _controller: GqAusUserBundle:User:editUser }
addUser:
    path:     /addUser/{roleType}
    defaults: { _controller: GqAusUserBundle:User:addUser }
checkEmailExist:
    path:     /checkEmailExist
    defaults: { _controller: GqAusUserBundle:User:checkEmailExist }
updateCourseStatus:
    path:     /updateCourseStatus
    defaults: { _controller: GqAusUserBundle:Applicant:updateCourseStatus }
faq:
    path:     /faq
    defaults: { _controller: GqAusUserBundle:User:faq }
pendingApplicantCount:
    path:    /pendingApplicantCount
    defaults: { _controller: GqAusUserBundle:Applicant:pendingApplicantCount }
unreadApplicantCount:
    path:    /unreadApplicantCount
    defaults: { _controller: GqAusUserBundle:Applicant:unreadApplicantCount }
sendMsgtoApplicant:
    path:     /sendMsgtoApplicant
    defaults:  { _controller: GqAusUserBundle:Applicant:sendMsgtoApplicant }
usersFromCourse:
    path:     /usersFromCourse
    defaults: { _controller: GqAusUserBundle:Message:usersFromCourse }
searchUsersListFrom:
    path:     /searchUsersListFrom
    defaults: { _controller: GqAusUserBundle:Message:searchUsersListFrom }
candidateProfile:
    path:     /candidateProfile/{courseCode}/{userId}
    defaults: { _controller: GqAusUserBundle:User:candidateProfile, courseCode: null }
updateprofileAjax:
    path:     /updateprofileAjax
    defaults: { _controller: GqAusUserBundle:User:updateprofileAjax }
updateNewPasswordAjax:
    path:     /updateNewPasswordAjax
    defaults: { _controller: GqAusUserBundle:User:updateNewPasswordAjax }
updateNewUserPasswordAjax:
    path:     /updateNewUserPasswordAjax
    defaults: { _controller: GqAusUserBundle:User:updateNewUserPasswordAjax }
updateNewUserAjax:
    path:     /updateNewUserAjax
    defaults: { _controller: GqAusUserBundle:User:updateNewUserAjax }
updateNewUserAjaxStatus:
    path:     /updateNewUserAjaxStatus
    defaults: { _controller: GqAusUserBundle:User:updateNewUserAjaxStatus }
updatepasswordAjax:
    path:     /updatepasswordAjax
    defaults: { _controller: GqAusUserBundle:User:updatepasswordAjax }
updateJobId:
    path:     /updateSthreeJobId/{jobId}
    defaults: { _controller: GqAusUserBundle:Evidence:updateSthreeJobId }
files:
    path:     /files/{courseCode}/{userId}
    defaults: { _controller: GqAusUserBundle:File:view, courseCode: null, userId: null  }
mobileRoleWiseFiles:
    path:     /rolewiseFiles/{courseCode}/{userId}
    defaults: { _controller: GqAusUserBundle:File:mobileRoleWiseView, courseCode: null, userId: null  }
filesAdd:
    path:     /addFiles
    defaults: { _controller: GqAusUserBundle:File:add}
updateFacilitator:
    path:     /updateFacilitator
    defaults: { _controller: GqAusUserBundle:Applicant:updateFacilitator }
updateAssessor:
    path:     /updateAssessor
    defaults: { _controller: GqAusUserBundle:Applicant:updateAssessor }
updateRto:
    path:     /updateRto
    defaults: { _controller: GqAusUserBundle:Applicant:updateRto }
changeReminderViewStatus:
    path:     /changeReminderViewStatus
    defaults: { _controller: GqAusUserBundle:Reminder:changeReminderViewStatus }
changeEvidenceViewStaus:
    path:     /changeEvidenceViewStaus
    defaults: { _controller: GqAusUserBundle:Evidence:changeEvidenceViewStaus }
userslog:
    path:     /userslog
    defaults: { _controller: GqAusUserBundle:User:userslog }
searchLogList:
    path:     /searchLogList
    defaults: { _controller: GqAusUserBundle:User:searchLogList }
checkUserNameExist:
    path:     /checkUserNameExist
    defaults: { _controller: GqAusUserBundle:User:checkUserNameExist }
checkUserNameExistOrNot:
    path:     /checkUserNameExistOrNot
    defaults: { _controller: GqAusUserBundle:User:checkUserNameExistOrNot }
signOffSheet:
    path:     /signOffSheet/{courseCode}/{userId}
    defaults: { _controller: GqAusUserBundle:Applicant:signOffSheet }
enrollment:
    path:     /enrollment
    defaults: { _controller: GqAusUserBundle:Enrollment:enrollment }
