
parameters:
    gq_aus_user.amazon_s3.class: AmazonS3    
    gq_aus_user.file_uploader.class: GqAus\UserBundle\Services\FileUploader
    
services:
#    api.example:
#        class: UserBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    kernel.listener.GqAusCacheListener:
        class: GqAus\UserBundle\EventListener\GqAusCacheListener
        tags:
        - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }
    UserService:
        class: GqAus\UserBundle\Services\UserService
        arguments: [@doctrine.orm.entity_manager, @service_container, '@mailer', '@GuzzleService']
    gq_aus_user.amazon_s3:
        class: %gq_aus_user.amazon_s3.class%
        arguments: [{ key: '%gq_aus_user.amazon_s3.aws_key%', secret: '%gq_aus_user.amazon_s3.aws_secret_key%' }]
    gq_aus_user.file_uploader:
        class: %gq_aus_user.file_uploader.class%
        arguments: ['@file_storage_filesystem', @doctrine.orm.entity_manager, @service_container, @UserService]
    EvidenceService:
        class: GqAus\UserBundle\Services\EvidenceService
        arguments: [@doctrine.orm.entity_manager, @service_container, @UserService]
    messageHelperService:
        class: GqAus\UserBundle\Services\MailService
        arguments: [@doctrine.orm.entity_manager, @service_container]
    app.twig_extension:
        class: GqAus\UserBundle\Twig\AppExtension
        arguments: [@UserService]
        tags:
            - { name: twig.extension }
    TokBox:
        class: GqAus\UserBundle\Services\TokBox
        arguments: [@doctrine.orm.entity_manager]
    NotesService:
        class: GqAus\UserBundle\Services\NotesService
        arguments: [@doctrine.orm.entity_manager, @service_container, @UserService]