
parameters:
    gq_aus_user.amazon_s3.class: Aws\S3\S3Client
    gq_aus_user.file_uploader.class: GqAus\UserBundle\Services\FileUploader
services:
#    api.example:
#        class: UserBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    EmailService:
        class: GqAus\UserBundle\Services\Email\EmailService
        arguments: [@doctrine.orm.entity_manager, @mailer, @service_container]
    UserCourseService:
        class: GqAus\UserBundle\Services\UserCourseService
        arguments: [@doctrine.orm.entity_manager]
    ReminderService:
        class: GqAus\UserBundle\Services\ReminderService
        arguments: [@doctrine.orm.entity_manager]
    AccountManagerDashboardService:
        class: GqAus\UserBundle\Services\AccountManagerDashboardService
        arguments: [@doctrine.orm.entity_manager]
    SetNewUserPasswordService:
        class: GqAus\UserBundle\Services\SetNewUserPasswordService
        arguments: [@doctrine.orm.entity_manager]
    ValidResponse:
        class: GqAus\UserBundle\Services\Response\ValidResponse
        arguments: []
    ErrorResponse:
        class: GqAus\UserBundle\Services\Response\ErrorResponse
        arguments: []
    HttpResponsesService:
        class: GqAus\UserBundle\Services\Response\HttpResponsesService
        arguments: [@ValidResponse, @ErrorResponse]
    kernel.listener.GqAusCacheListener:
        class: GqAus\UserBundle\EventListener\GqAusCacheListener
        tags:
        - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }
    UserService:
        class: GqAus\UserBundle\Services\UserService
        arguments: [@doctrine.orm.entity_manager, @service_container, '@mailer', '@GuzzleService', '@CoursesService', '@SQSService', @EmailService]
    CourseFileService:
        class: GqAus\UserBundle\Services\UserCourse\FileService
        arguments: [@doctrine.orm.entity_manager]
    gq_aus_user.amazon_s3:
        class: %gq_aus_user.amazon_s3.class%
        arguments: [{ key: '%gq_aus_user.amazon_s3.aws_key%', secret: '%gq_aus_user.amazon_s3.aws_secret_key%', region: 'us-west-2', version: 'latest', scheme: 'http' }]
    gq_aus_user.file_uploader:
        class: %gq_aus_user.file_uploader.class%
        arguments: ['@file_storage_filesystem', @doctrine.orm.entity_manager, @service_container, @UserService]
    EvidenceService:
        class: GqAus\UserBundle\Services\EvidenceService
        arguments: [@doctrine.orm.entity_manager, @service_container, @UserService]
    messageHelperService:
        class: GqAus\UserBundle\Services\MailService
        arguments: [@doctrine.orm.entity_manager, @service_container]
    app.twig_extension:
        class: GqAus\UserBundle\Twig\AppExtension
        arguments: [@UserService]
        tags:
            - { name: twig.extension }
    TokBox:
        class: GqAus\UserBundle\Services\TokBox
        arguments: [@doctrine.orm.entity_manager]
    NotesService:
        class: GqAus\UserBundle\Services\NotesService
        arguments: [@doctrine.orm.entity_manager, @service_container, @UserService]
    templating.engine.twig:
        class: GqAus\UserBundle\Twig\TwigEngine
        arguments: [@twig, @templating.name_parser, @templating.locator, @mobile_detect.mobile_detector]
    SQSService:
        class: GqAus\UserBundle\Services\SQSService
        arguments: [@service_container]
