gq_aus_home_homepage:
    path:     /dashboard
    defaults: { _controller: GqAusHomeBundle:Default:index }
download:
    path:     /download/{file}
    defaults:  { _controller: GqAusHomeBundle:Default:download }
updateCondition:
    path:     /updateCondition
    defaults:  { _controller: GqAusHomeBundle:Default:updateCondition }
updateUnitElective:
    path:     /updateUnitElective
    defaults:  { _controller: GqAusHomeBundle:Courses:updateUnitElective }
addEvidence:
    path:     /addEvidence
    defaults:  { _controller: GqAusHomeBundle:Courses:addEvidence }
qualificationDetails:
    path:     /qualificationDetails/{id}
    defaults:  { _controller: GqAusHomeBundle:Courses:index }
qualificationUnits:
    path:     /qualificationDetails/{id}/{page}
    defaults:  { _controller: GqAusHomeBundle:Courses:index }
qualifications:
    path:     /qualifications
    defaults:  { _controller: GqAusHomeBundle:Courses:qualifications }
addEvidences:
    path:     /addEvidences
    defaults:  { _controller: GqAusUserBundle:Evidence:add }
evidences:
    path:     /evidences
    defaults:  { _controller: GqAusUserBundle:Evidence:view }
unauthorized:
    path:     /unauthorized
    defaults: { _controller: GqAusHomeBundle:Default:unauthorized }      
submitUnitForReview:
    path:     /submitUnitForReview
    defaults:  { _controller: GqAusHomeBundle:Courses:submitUnitForReview }
unreadEvidenceCount:
    path:    /unreadEvidenceCount
    defaults: { _controller: GqAusHomeBundle:Default:unreadEvidenceCount }
getUnits:
    path:    /units/getUnits
    defaults: { _controller: GqAusHomeBundle:Courses:getUnits }
uploadElectiveUnits:
    path:    /uploadElectiveUnits
    defaults: { _controller: GqAusHomeBundle:Courses:uploadElectiveUnits }
updateSelfAssessment:
    path:    /updateSelfAssessment
    defaults: { _controller: GqAusHomeBundle:Courses:updateSelfAssessment }
getUnitDetails:
    path:    /units/getUnitDetails
    defaults: { _controller: GqAusHomeBundle:Courses:getUnitDetails }
getUserUnits:
    path: /units/getUserUnits
    defaults: { _controller: GqAusHomeBundle:Courses:getUserUnits }
updateSelectedElectiveUnits:
    path: /units/updateSelectedElectiveUnits
    defaults: { _controller: GqAusHomeBundle:Courses:updateSelectedElectiveUnits }