download:
    path:     /download/{file}
    defaults:  { _controller: GqAusHomeBundle:Default:download }
updateCondition:
    path:     /updateCondition
    defaults:  { _controller: GqAusHomeBundle:Default:updateCondition }
updateUnitElective:
    path:     /updateUnitElective
    defaults:  { _controller: GqAusHomeBundle:Courses:updateUnitElective }
addEvidence:
    path:     /addEvidence
    defaults:  { _controller: GqAusHomeBundle:Courses:addEvidence }
qualificationDetails:
    path:     /qualificationDetails/{id}/{userId}
    defaults:  { _controller: GqAusHomeBundle:Courses:index, userId:null }
qualificationUnits:
    path:     /qualificationDetails/{id}/{page}
    defaults:  { _controller: GqAusHomeBundle:Courses:index }
qualifications:
    path:     /qualifications
    defaults:  { _controller: GqAusHomeBundle:Courses:qualifications }
addEvidences:
    path:     /addEvidences
    defaults:  { _controller: GqAusUserBundle:Evidence:add }
evidences:
    path:     /evidences
    defaults:  { _controller: GqAusUserBundle:Evidence:view }
unauthorized:
    path:     /unauthorized
    defaults: { _controller: GqAusHomeBundle:Default:unauthorized }      
submitUnitForReview:
    path:     /submitUnitForReview
    defaults:  { _controller: GqAusHomeBundle:Courses:submitUnitForReview }
unreadEvidenceCount:
    path:    /unreadEvidenceCount
    defaults: { _controller: GqAusHomeBundle:Default:unreadEvidenceCount }
getUnits:
    path:    /units/getUnits
    defaults: { _controller: GqAusHomeBundle:Courses:getUnits }
uploadElectiveUnits:
    path:    /uploadElectiveUnits
    defaults: { _controller: GqAusHomeBundle:Courses:uploadElectiveUnits }
updateSelfAssessment:
    path:    /updateSelfAssessment
    defaults: { _controller: GqAusHomeBundle:Courses:updateSelfAssessment }
getUnitDetails:
    path:    /units/getUnitDetails
    defaults: { _controller: GqAusHomeBundle:Courses:getUnitDetails }
getUserUnits:
    path: /units/getUserUnits
    defaults: { _controller: GqAusHomeBundle:Courses:getUserUnits }
updateSelectedElectiveUnits:
    path: /units/updateSelectedElectiveUnits
    defaults: { _controller: GqAusHomeBundle:Courses:updateSelectedElectiveUnits }
downloadSelectedElectiveUnits:
    path: /units/downloadSelectedElectiveUnits/{unitId}/{detailsType}
    defaults: { _controller: GqAusHomeBundle:Courses:downloadSelectedElectiveUnits }
getUploadDetails:
    path: /units/getUploadDetails
    defaults: { _controller: GqAusHomeBundle:Courses:getUploadDetails }
getEvidencesByUnit:
    path: /units/getEvidencesByUnit
    defaults: { _controller: GqAusHomeBundle:Courses:getEvidencesByUnit }
unitDetails:
    path: /qualification/unitDetails/{unitCode}/{courseCode}/{userId}
    defaults: {_controller: GqAusHomeBundle:Courses:getCourseUnitDetails, userId:null}
getUnitInfo:
    path: /qualification/getUnitInfo
    defaults: {_controller: GqAusHomeBundle:Courses:getUnitInfo}
getEvidenceLibrary:
    path: /units/getEvidenceLibrary
    defaults: { _controller: GqAusHomeBundle:Courses:getEvidenceLibrary }
getNotes:
    path: /units/getNotes
    defaults: { _controller: GqAusHomeBundle:Courses:getNotes }  
saveNotes:
    path: units/saveNotes
    defaults: { _controller: GqAusHomeBundle:Courses:saveNotes }  
acknowledgeNote:
    path: units/acknowledgeNote
    defaults: { _controller: GqAusHomeBundle:Courses:acknowledgeNote }     
