services:
#    api.example:
#        class: UserBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    UserService:
        class: GqAus\UserBundle\Services\UserService
        arguments: [@doctrine.orm.entity_manager, @service_container, '@mailer']