services:
#    api.example:
#        class: UserBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    UserService:
        class: GqAus\UserBundle\Services\UserService
        arguments: [@doctrine.orm.entity_manager, @service_container, '@mailer', '@GuzzleService', '@CoursesService', '@SQSService']
    CoursesService:
        class: GqAus\HomeBundle\Services\CoursesService
        arguments: [@doctrine.orm.entity_manager, @service_container, '@mailer', '@GuzzleService']
    RtoService:
        class: GqAus\HomeBundle\Services\RtoService
        arguments: [@doctrine.orm.entity_manager, @service_container, @ApiService]
    ApiService:
        class: GqAus\HomeBundle\Services\ApiService
        arguments: [@service_container, '@GuzzleService', @XMLService]    
    XMLService:
        class: GqAus\HomeBundle\Services\XMLService
        arguments: []    
    GuzzleService:
        class: %guzzle.http_client.class%
        arguments: []
    templating.engine.twig:
        class: GqAus\UserBundle\Twig\TwigEngine
        arguments: [@twig, @templating.name_parser, @templating.locator, @mobile_detect.mobile_detector]
