services:
#    api.example:
#        class: UserBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    UserService:
        class: GqAus\UserBundle\Services\UserService
        arguments: [@doctrine.orm.entity_manager, @service_container, '@mailer', '@GuzzleService']
    CoursesService:
        class: GqAus\HomeBundle\Services\CoursesService
        arguments: [@doctrine.orm.entity_manager, @service_container, '@mailer', '@GuzzleService']
    GuzzleService:
        class: %guzzle.http_client.class%
        arguments: []
    templating.engine.twig:
        class: GqAus\UserBundle\Twig\TwigEngine
        arguments: [@twig, @templating.name_parser, @templating.locator, @mobile_detect.mobile_detector]
